#!/bin/bash

if [ ! -d ${MYSQLENV_VERSION_INSTALL_DIR} ]; then
  mkdir ${MYSQLENV_VERSION_INSTALL_DIR}
fi

if [ -f ${VERSION_FILE} -a -d ${MYSQLENV_VERSION_INSTALL_DIR}/$(cat ${VERSION_FILE}) ]; then
  PATH=${PATH}:${MYSQLENV_VERSION_INSTALL_DIR}/$(cat ${VERSION_FILE})/bin
  export PATH=${PATH}
else
  echo "version not specified" >&2 
fi
