#!/bin/bash

usage(){
  echo "Usage: mysqlenv global <version>" >&2
  exit 1
}

[ -z $1 ] && usage

if [ -d ${MYSQLENV_VERSION_INSTALL_DIR}/$1 ]; then
  echo $1 > $VERSION_FILE
  PATH=${MYSQLENV_VERSION_INSTALL_DIR}/$(cat ${VERSION_FILE})/bin:${PATH}
  echo "export PATH=$PATH"
else
  echo "mysqlenv: $MYSQL_VERSION not installed." >&2
fi
