#!/bin/bash

if [ ! -f $VERSION_FILE ]; then
  echo "mysqlenv: Version file doesn't exists.\nTry 'mysqlenv global <version>' and set MySQL version." >&2
  exit 1
fi

MYSQL_VERSION=$(cat ${VERSION_FILE})

if [ -d ${MYSQLENV_VERSION_INSTALL_DIR}/${MYSQL_VERSION} ]; then
  echo $MYSQL_VERSION
else
  echo "mysqlenv: $MYSQL_VERSION not installed."
fi
