#!/bin/bash -x

usage(){
  cat <<EOS
Usage: mysqlenv start [version]
EOS
  exit $1
}

if [ -z $FLAG_ALL]; then
  for version_dir in $MYSQLENV_VERSION_INSTALL_DIR/*
  do
    version=$(basename $version_dir)
    START_SCRIPT=$(find ${MYSQLENV_VERSION_INSTALL_DIR}/${version} -name "mysql.server")
    $START_SCRIPT start
  done
else
  if [ -z $1 ]; then
    VERSION=$(sh mysqlenv-version)
  else
    VERSION=$1
  fi

  if [ -z $VERSION ]; then
    echo "mysqlenv: version not specified. install and set mysql global use version."
    usage 1
  fi

  if [ ! -d ${MYSQLENV_VERSION_INSTALL_DIR}/${VERSION} ]; then
    echo "mysqlenv: version $VERSION not installed."
    usage 1
  fi

  START_SCRIPT=$(find ${MYSQLENV_VERSION_INSTALL_DIR}/${VERSION} -name "mysql.server")
  $START_SCRIPT start
fi
